name: Build APK and Notify
on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: dev
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Debug - List repository contents
      run: |
        echo "Current directory:"
        pwd
        echo "Repository contents:"
        ls -la
        echo "Looking for gradlew specifically:"
        find . -name "gradlew*" -type f
        
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Build APK
      run: ./gradlew assembleRelease
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/*.apk
