name: Auto Build Android

on:
  push:
    branches: [ dev ]

jobs:
  build-and-notify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: android-actions/setup-android@v3
    
    - name: Build APK
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug
    
    - name: Email Result
      uses: dawidd6/action-send-mail@v3
      if: always()
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "${{ job.status == 'success' && '✅ BUILD SUCCESS' || '❌ BUILD FAILED' }}"
        to: ${{ secrets.NOTIFICATION_EMAIL }}
        from: ${{ secrets.EMAIL_USERNAME }}
        body: |
          Build ${{ job.status }} for commit ${{ github.sha }}
          View: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
